config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users
  
  resources :movies do
  	collection do 
  		get 'search'
  	end
  	resources :reviews, except:[:index, :show]
  end

  root to: "movies#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	#searchkick
	validates :title, :description, :movie_length, :director, :rating, presence:true
	belongs_to :user
	has_many :reviews

	has_attached_file :image, styles: { medium: "400x600#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :authenticate_user!, except:[:index,:show]

  before_action :set_id, only:[:edit, :show, :update,:destroy]

  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end    
  end
  
  def index
    @movies = Movie.all
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at Desc")

    if @review.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def create
    @movie = current_user.movies.build(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "Movie is successfully created for review"
    else
      render 'new'
    end
  end

  

  def update
    if @movie.update(movie_params)
      redirect_to movies_path, notice: "Movie is successfully updated"
    else
      render 'new'
    end
  end

  def destroy
    @movie.destroy
    redirect_to @movie, notice: "Movie is deleted"
  end
  private 
  
  def movie_params
    params.require(:movie).permit(:title, :description, :movie_length,:director,:rating, :image)
  end

  def set_id
    @movie = Movie.find(params[:id])    
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :set_review, only:[:edit, :update, :destroy]
	before_action :set_movie
	before_action :authenticate_user!, except:[:index]
	
	def new
		@review = Review.new		
	end

	def edit	
	end

	def create
		@review = Review.new(review_params)
		@review.user_id = current_user.id
		@review.movie_id = @movie.id
		if @review.save
		redirect_to movie_path(@movie)
		else
		render 'new'
		end
	end

	def update
		@review = Review.update(review_params)
		redirect_to movie_path(@movie)		
	end

	def destroy
		if @review.destroy
			# redirect_to movie_path(@movie)
		end
	end

	private
	def review_params
		params.require(:review).permit(:rating, :comment)		
	end

	def set_review
		@review = Review.find(params[:id])		
	end

	def set_movie
		@movie = Movie.find(params[:movie_id])		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <!-- <a class="navbar-brand" id="logo" href="#">Movie Review</a> -->
      <%=link_to "Movie Review", root_path, class: "navbar-brand", id: "logo"%>
    </div>
    <ul class="nav navbar-nav">
      <li><%=link_to "New Movie", new_movie_path%></li>
    </ul>
    <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: " search" do %>
    	<p>
    		<%= text_field_tag :search, params[:search], class: "form-control"%>
    		<%= submit_tag "Search", name: nil,class: "btn btn-default"%>
    	</p>
    <% end -%>
  </div>
</nav>

  
<!-- <div class="container">
  <h3>Basic Navbar Example</h3>
  <p>A navigation bar is a navigation header that is placed at the top of the page.</p>
</div>
 -->

app/views/layouts/application.html.erb
<p class="navbar-text-pull-right">
	<%if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong>
		<%=link_to "Edit Profile", edit_user_registration_path, class: "navbar-link"%> |
		<%=link_to "Log out", destroy_user_session_path,method: :delete, class: "navbar-link"%> |
	<%else%>
		<%=link_to "Sign Up", new_user_registration_path, class: "navbar-link"%> |
		<%=link_to "Log in", new_user_session_path, class: "navbar-link"%> |
	<% end -%>
</p>
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/header'%>
      <div class="container">
	    	<%flash.each do |name, msg|%>
	      <%= content_tag(:div, msg, class: "alert alert-info")%>
	   	 <% end -%>
	    <%= yield %>
   	 </div>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="movie-form">
		<%=form_for @movie, html: { multipart: true } do |f| %>
			<% if @movie.errors.any? %>
				<ul>
					<%@movie.errors.full_messages.each do |error|%>
						<li>
							<%= error%>
						</li>
					<% end -%>
				</ul>
			<% end -%>

			<div class="well well-sm">
				<p class="movie-title">
					<%=f.label :title, "Title:"%><br>
					<%=f.text_field :title%>					
				</p>
				<p class="movie-description">
					<%=f.label :description, "Description:"%><br>
					<%=f.text_area :description%>					
				</p>
				<p class="movie-length">
					<%=f.label :movie_length, "Length:"%><br>
					<%=f.text_field :movie_length%>					
				</p>
				<p class="movie-director">
					<%=f.label :director, "Director"%><br>
					<%=f.text_field :director%>					
				</p>
				<p class="movie-rating">
					<%=f.label :rating, "Rating:"%><br>
					<%=f.text_field :rating%>	
				</p>
				<p class="field">
					<%=f.label :image%><br>
					<%= f.file_field :image %>
				</p>
  							
				
				<p class="actions">
					<%=f.submit%><br>
				</p>
				<%=link_to "Cancle", movies_path%> |
			</div>
		<% end -%>
	</div>

app/views/movies/edit.html.erb
<h2>You can edit your movie here</h2>
<%=render 'form'%>
<%=link_to 	"Back", movie_path(@movie), class: "btn btn-sm btn-primary"%>

app/views/movies/index.html.erb
<% if !user_signed_in?%>
	<div class="jumbotron">
		<h3>Review your favourite movie</h3>
			<p><%= link_to "Sign_Up to write a review", new_user_registration_path, class: "btn btn-primary btn-sm"  %></p>		
	</div>
<%end%>

<div class="row">
	<%@movies.each do |movie|%>
		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%=link_to (image_tag movie.image.url(:medium),class: 'image'), movie%>				
			</div>			
		</div>
	<% end -%>	
</div>
				
					

app/views/movies/new.html.erb
<h2>Create a new movie</h2>
	<%=render 'form'%>

app/views/movies/show.html.erb
<div class="pannel pannel-default">
	<div class="pannel-body">
		<div class="row">
				<div class="col-md col-md-4">
					<%=image_tag @movie.image.url(:medium)%>
						<div class="star-rating" data-score=<%=@avg_review %> > </div>
							<em><%= "#{@reviews.length} reviews"%></em>
						<div class="table-responsive">
							<table class="table">
								<tbody>
									<tr>
										<td><h4 style="color:Tomato;">Title:</h4></td>
										<td><%=@movie.title%></td>
									</tr>
									<tr>
										<td><h4 style="color:Tomato;">Description:</h4></td>
										<td><%=simple_format(@movie.description)%></td>
									</tr>
									<tr>
										<td><h4 style="color:Tomato;">Length:</h4></td>
										<td><%=(@movie.movie_length)%></td>
									</tr>
									<tr>
										<td><h4 style="color:Tomato;">Director:</h4></td>
										<td><%=(@movie.director)%></td>
									</tr>
									<tr>
										<td><h4 style="color:Tomato;">Rating:</h4></td>
										<td><%=(@movie.rating)%></td>
									</tr>
								</tbody>								
							</table>	
							<%=link_to "Write a review", new_movie_review_path(@movie)%>
						</div>
					</div>
			<div class="col-md-7 col-md-offset-1">
				<h1 class="review_title"><%= @movie.title%></h1>
				<p>
					<%=@movie.description%>
				</p>
				<% if @reviews.blank? %>
					<h3>No Reviews Yet,please write a review</h3>
					<%=link_to "Write a review", new_movie_review_path(@movie), 
											class: "btn btn-sm btn-danger"%>
				<% else %>
					<% @reviews.each do |review|%>
						<div class="review">
							<div class="star-rating" data-score=<%=review.rating %> > </div>
							 	<%=review.comment %>
						</div>
					<% end -%>
				<% end -%>						
			</div>
		</div>
	</div>	
</div>
<%= link_to "Edit", edit_movie_path(@movie),class: "btn btn-sm btn-primary"%>
<%= link_to "Delete", movie_path(@movie),method: :delete,data:{confirm: "Are you sure?"},
								class: "btn btn-sm btn-danger"%>
<%= link_to "Index", movies_path,class: "btn btn-sm btn-primary"%>

<script>
	$('.star-rating').raty({
		path: '/assets/',
		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		}
	});
</script>

app/views/reviews/_form.html.erb
<div class="review-form">
	<%=form_for [@movie, @review] do |f| %>
			<% if @review.errors.any? %>
				<ul>
					<%@review.errors.full_messages.each do |error|%>
						<li>
							<%= error%>
						</li>
					<% end -%>
				</ul>
			<% end -%>
		<div class="well well-sm">
			<p class="review-rating">
				<div id="star-rating"></div>					
			</p>
			<p class="comment">
				<%=f.label :comment, "Comment:"%><br>
				<%=f.text_area :comment%>					
			</p>			
				
			<p class="actions">
				<%=f.submit%><br>
			</p>
			<%=link_to "Cancle",movie_path(@movie)%> |
		</div>
	<% end -%>
		
</div>
<script>
			$('#star-rating').raty({
				path: '/assets/',
				score:'review-[rating]'
			});
		</script>

app/views/reviews/edit.html.erb
<%=render 'form'%>
<%=link_to 	"Back", movie_path(@movie), class: "btn btn-sm btn-primary"%>

app/views/reviews/new.html.erb
<h2>New Review</h2>
<%= render 'form'%>